travels_service:
    resource: "@TravelsServiceBundle/Controller/"
    type:     annotation
    prefix:   /

travels_main:
    resource: "@TravelsMainBundle/Controller/"
    type:     annotation
    prefix:   /
